targets:
  $default:
    builders:
      chopper_generator:
        generate_for:
          include:
            - lib/data/services/**.dart
            - lib/data/core/services/**.dart
      go_router_builder:
        generate_for:
          include:
            - lib/app/router/**.dart