targets:
  $default:
    builders:
      chopper_generator:
        generate_for:
          include:
            - lib/modules/home/data/services/**.dart
            - lib/modules/login/data/services/**.dart
            - lib/modules/signup/data/services/**.dart
      go_router_builder:
        generate_for:
          include:
            - lib/app/router/**.dart