name: tu_home
description: Tu Home App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  chopper: ^7.0.8
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.4
  go_router: ^12.0.1
  hydrated_bloc: ^9.1.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  services:
    path: packages/services
  lottie: ^2.7.0
  flutter_adaptive_scaffold: ^0.1.7+1


dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  chopper_generator: ^7.0.6
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.3.3
  json_serializable: ^6.7.1
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/lottie/
  fonts:
    - family: Catamaran
      fonts:
        - asset: assets/fonts/Catamaran-Black.ttf
        - asset: assets/fonts/Catamaran-Bold.ttf
        - asset: assets/fonts/Catamaran-ExtraBold.ttf
        - asset: assets/fonts/Catamaran-ExtraLight.ttf
        - asset: assets/fonts/Catamaran-Light.ttf
        - asset: assets/fonts/Catamaran-Medium.ttf
        - asset: assets/fonts/Catamaran-Regular.ttf
        - asset: assets/fonts/Catamaran-SemiBold.ttf
        - asset: assets/fonts/Catamaran-Thin.ttf

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true