name: tu_home
description: Tu Home App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  chopper: ^7.0.8
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.4
  go_router: ^12.0.0
  hydrated_bloc: ^9.1.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  ui:
    path: packages/ui
  services:
    path: packages/services


dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  chopper_generator: ^7.0.6
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.3.3
  json_serializable: ^6.7.1
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
  generate: true
