name: tu_home
description: Tu Home App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  chopper: ^7.0.9
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.4
  go_router: ^13.2.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  logger: ^2.1.0
  shared_preferences: ^2.2.2
  injectable: ^2.3.2
  flutter_animate: ^4.3.0
  fast_cached_network_image: ^1.2.8
  path_provider: ^2.1.1
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  syncfusion_flutter_charts: ^25.1.35


dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.7
  chopper_generator: ^7.0.6
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.4.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  flutter_launcher_icons: ^0.13.1
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true
  # generate: true
  assets:
    - assets/images/
  fonts:
    - family: Catamaran
      fonts:
        - asset: assets/fonts/Catamaran-Black.ttf
        - asset: assets/fonts/Catamaran-Bold.ttf
        - asset: assets/fonts/Catamaran-ExtraBold.ttf
        - asset: assets/fonts/Catamaran-ExtraLight.ttf
        - asset: assets/fonts/Catamaran-Light.ttf
        - asset: assets/fonts/Catamaran-Medium.ttf
        - asset: assets/fonts/Catamaran-Regular.ttf
        - asset: assets/fonts/Catamaran-SemiBold.ttf
        - asset: assets/fonts/Catamaran-Thin.ttf

flutter_gen:
  output: lib/app/ui/assets/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true